# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_int <- function(N) {
    .Call(`_bcdc_sample_int`, N)
}

sample_int_vec <- function(N, size) {
    .Call(`_bcdc_sample_int_vec`, N, size)
}

stick_break <- function(x) {
    .Call(`_bcdc_stick_break`, x)
}

symmat_rbeta <- function(alpha, beta) {
    .Call(`_bcdc_symmat_rbeta`, alpha, beta)
}

safe_exp <- function(log_prob) {
    .Call(`_bcdc_safe_exp`, log_prob)
}

my_sampler <- function(prob_vec) {
    .Call(`_bcdc_my_sampler`, prob_vec)
}

sample_index <- function(prob) {
    .Call(`_bcdc_sample_index`, prob)
}

rgamma_vec <- function(shape) {
    .Call(`_bcdc_rgamma_vec`, shape)
}

rbeta_vec <- function(alpha, beta) {
    .Call(`_bcdc_rbeta_vec`, alpha, beta)
}

rdirichlet <- function(theta) {
    .Call(`_bcdc_rdirichlet`, theta)
}

